services:
  - type: web
    name: temperature-prediction-api
    env: docker
    dockerfilePath: ./API/Dockerfile  # <-- Path from root
    region: frankfurt
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MODEL_PATH
        value: ./temperature_ridge_model.pkl